name: Build Docker image and push

on:
  workflow_dispatch:
  push:
    branches: [ "aweminds" ]
  pull_request:
    branches: [ "aweminds" ]

env:
  REGISTRY: registry.cn-shanghai.aliyuncs.com
  IMAGE_NAME: aweminds-webui
  
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Github Container Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

      - uses: docker/setup-buildx-action@v2
      
      - name: Docker Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          file: ./Dockerfile_update
          #tags: ${{ steps.meta.outputs.tags }}
          tags: |
              registry.cn-shanghai.aliyuncs.com/aweminds/aweminds-webui:latest-amd64
              registry.cn-shanghai.aliyuncs.com/aweminds/aweminds-webui:${{ steps.date.outputs.today }}
          labels: ${{ steps.meta.outputs.labels }}
          
  trigger-deploy-to-248:
    needs: build_and_publish
    runs-on: ubuntu-latest
    outputs:
        CONTINUE_JOBS: ${{ steps.manual-trigger.outputs.CONTINUE_JOBS }}
    steps:
      - name: manual-trigger
        id: manual-trigger
        uses: benhamiltonpro/manual-trigger@v1
        with:
          RUN_NAME: "deploying-248"        
  
  deploying-248:
      needs: trigger-deploy-to-248
      if: ${{ needs.trigger-deploy-to-248.outputs.CONTINUE_JOBS == 'true' }}
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to fantuyun 248
          uses: easingthemes/ssh-deploy@main
          env:
            REMOTE_HOST: ${{ secrets.FANTUYUN_248_SERVER_HOST }}
            REMOTE_USER: ${{ secrets.FANTUYUN_248_SERVER_USER }}
            SSH_PRIVATE_KEY: ${{ secrets.FANTUYUN_248_PRIVATE_KEY }}
            SCRIPT_BEFORE: |
              /app/update.sh
  
  trigger-deploy-to-253:
    needs: deploying-248
    runs-on: ubuntu-latest
    outputs:
        CONTINUE_JOBS: ${{ steps.manual-trigger.outputs.CONTINUE_JOBS }}
    steps:
      - name: manual-trigger
        id: manual-trigger
        uses: benhamiltonpro/manual-trigger@v1
        with:
          RUN_NAME: "deploying-253"
  
  deploying-253:
      needs: trigger-deploy-to-253
      if: ${{ needs.trigger-deploy-to-253.outputs.CONTINUE_JOBS == 'true' }}
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to fantuyun 253
          uses: easingthemes/ssh-deploy@main
          env:
            REMOTE_HOST: ${{ secrets.FANTUYUN_253_SERVER_HOST }}
            REMOTE_USER: ${{ secrets.FANTUYUN_253_SERVER_USER }}
            SSH_PRIVATE_KEY: ${{ secrets.FANTUYUN_253_PRIVATE_KEY }}
            SCRIPT_BEFORE: |
              /app/update.sh
